version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb_test
    restart: unless-stopped  # Keep the container running for testing
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root_password  # Replace with a stronger password for testing
      MYSQL_DATABASE: test_db             # Database name for testing
      MYSQL_USER: test_user               # User for testing
      MYSQL_PASSWORD: test_password       # Password for the testing user
    volumes:
      - ./data/mariadb:/var/lib/mysql  # Persist data for the MariaDB container


  postgres:
    image: postgres:latest
    container_name: postgres_test
    restart: unless-stopped  # Keep the container running for testing
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: test_user           # User for testing
      POSTGRES_PASSWORD: test_password   # Password for the testing user
      POSTGRES_DB: test_db                # Database name for testing
    volumes:
      - ./data/postgres:/var/lib/postgresql/data  # Persist data for the PostgreSQL container


  adminer:
    image: adminer:latest
    container_name: adminer_test
    restart: unless-stopped  # Keep the container running for testing
    ports:
      - 8080:8080
    depends_on:
      - mariadb
      - postgres