import type { Metadata } from "next";
import { Inter, Open_Sans } from "next/font/google";
import "./globals.css";
import NavIndex from "../components/header";
import Footer from "../components/footer";
import Toast from "@/components/ui/toast";
import Script from "next/script";

const os = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Script  src="node_modules/@material-tailwind/html@latest/scripts/dialog.js" />
      <body className={os.className}>
        <NavIndex />
        <main className="flex-grow w-screen mx-auto overflow-hidden bg-blue-gray-50">
          {children}
        </main>
        <Footer />
        <Toast />
      </body>
    </html>
  );
}
